### ISSUE TITLE
Configure project to use resource packages.

### ISSUE THREAD

**Issue by MikeMMattinson** [MikeMMattinson/space2d_java_3#26]
Configure the java project to use resource package folders and then make sure they access correctly using the .jar build file.

**Comment by MikeMMattinson** [comment]
Two problems:
- [ ] Planet.draw() something wrong...
- [ ] Got Null exception when running using .jar file

**Comment by MikeMMattinson** [comment]
ok, found the error in Planet.darw(), i had changed the attribute for planet image to pImage.
![image](https://github.com/MikeMMattinson/space2d_java_3/assets/7810463/225e4f99-9eb8-4cd7-8f90-459a442330c8)

**Comment by MikeMMattinson** [comment]
Still have the other issue:
```
W:\code\git-clone\space2d_java_3>java -jar space2d_java_3.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356)
        at main.entity.planets.Planet.readPlanetResource(Planet.java:525)
        at main.entity.planets.Planet.<init>(Planet.java:298)
        at main.entity.planets.Planets.<init>(Planets.java:40)
        at main.GamePanel.<init>(GamePanel.java:45)
        at main.GameLauncher.<clinit>(GameLauncher.java:21)
```

**Comment by nickmattinson** [comment]
the code that pulls the image will be case sensitive, and from what I know about images, I think they have to be in the same src folder.

**Comment by MikeMMattinson** [comment]
i think the resources are working and I know how to add things and how to look for the correct resource. 
```

/*
 * Author: Mike
 * Updated: 9/NOv/23
 * Issue: #26
 */

public class ImageUtility {

    public BufferedImage lookForResource(String imgPackage, String imgName) throws ImageNotFoundException {
        BufferedImage img = null;
        String imgPackageAndName = String.format("/%s/%s", imgPackage, imgName);
        try {
            img = ImageIO.read(getClass().getResourceAsStream(imgPackageAndName));

        } catch(IOException e) {
            // Wrap the exception and add more details
            throw new ImageNotFoundException(imgPackage, imgName);
        }
        return img;
    }
```

**Comment by MikeMMattinson** [comment]
```
    /*
     * Author: Mike
     * Updated: 11/Nov/23
     * Issue: #26
     */
    public void getPlayerImages() {
        ImageUtility iu = new ImageUtility();
        try {
            up1 = iu.lookForResource("player", "rocket_64.png");  
            thrust = iu.lookForResource("player", "rocket_thruster_64.png");
            decel = iu.lookForResource("player", "rocket_decel_64.png");
            bullet = iu.lookForResource("player", "rocket_64.png");
        } catch(IOException e) {
            e.printStackTrace();
        }
    }
```
